---
- hosts: localhost
  connection: local

  tasks:
  - name: install packages
    become: true  
    package:
        name:
          - htop
          - neovim
          - firefox
          - git
          - sway
          - waybar
          - vulkan-radeon
          - ttf-font-awesome
          - transmission-qt
          - spotify-launcher
          - mesa
          - mako
          - gammastep
          - thunar
          - amdvlk
          - alacritty
          - polkit-gnome

  - name: copy config files
    copy: 
        src: files/config
        dest: /home/mateusz/.config
        owner: mateusz
        group: mateusz
     
  - name: clone yay
    git:
        repo: https://aur.archlinux.org/yay-bin.git
        dest: /home/mateusz/yay
        update: true

  - name: install yay
    become: false
    become_user: mateusz
    command:
      chdir: /home/mateusz/yay
      cmd: "makepkg -sfi --noconfirm"
      creates: /usr/bin/yay

  - name: copy bash_profile
    copy:
        src: files/.bash_profile
        dest: /home/mateusz
        owner: mateusz
        group: mateusz

  - name: add ansible user
    become: true
    user:
      name: ansibleupdate
      system: yes
    
  - name: set sudo for ansible user
    become: true
    copy:
      src: files/sudoer_ansibleupdate
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pulll as cron
    become: true
    cron:
      name: ansible auto-provision
      user: sudoer_ansibleupdate
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/Zawisza-Czarny/ansible_setup.git
