---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install packages
      package:
        name:
          - htop
          - neovim
          - firefox
          - git
          - sway
          - waybar
          - vulkan-radeon
          - qemu
          - virt-manager
          - virt-viewer
          - dnsmasq
          - bridge-utils
          - libguestfs
          - ebtables
          - vde2
          - openbsd-netcat
          - ttf-font-awesome
          - transmission-qt
          - spotify-launcher
          - mesa
          - mako
          - chiaki
          - gammastep
          - thunar
          - amdvlk
          - alacritty
          - polkit-gnome

    - name: copy config files
      copy: 
        src: files/config/
        dest: ~/.config/
        owner: mateusz
        group: mateusz
     
    - name: clone yay
      git:
        repo: https://aur.archlinux.org/yay-bin.git
        dest: "{{ srcdir }}/yay"
        update: true

    - name: install yay
      command:
        chdir: "{{ srcdir }}/yay"
        cmd: "makepkg -sfi --noconfirm"
        creates: /usr/bin/yay

    - name: copy bash_profile
      copy:
      src: files/.bash_profile
      dest: ~/
      owner: mateusz
      group: mateusz
